- name: create folder
  community.general.jenkins_job:
      config: "{{ lookup('file', '/tmp/jenkins_job.xml') }}"
      name: "{{item}}"
      password: "{{jenkins_password}}"
      url: http://172.31.8.108:8080
      user: admin
  loop:
   - cipipeline    

- name: Include task list in play
  ansible.builtin.include_tasks:
        file: pipeline.yml
  loop:
    - {name: "frontend", dir: "cipipeline"}     