- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/folder.xml') }}"
      name: "{{item}}"
      password: "{{jenkins_password}}"
      url: http://172.31.8.108:8080
      user: admin
  loop: "{{ folders }}"
   

- name: Include task list in play
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loop: "{{ pipeline_jobs }}"
   