  - name: create config file
    ansible.builtin.template:
      src: jenkins_job.xml
      dest: /tmp/jenkins_job.xml
 
  - name: Create a jenkins job using basic authentication
    community.general.jenkins_job:
      config: "{{ lookup('file', '/tmp/jenkins_job.xml') }}"
      name: "{{item.name}}/{{item.dir }}"
      password: "{{jenkins_password}}"
      url: http://172.31.8.108:8080
      user: admin
     